### ISSUE TITLE
Missing Documentation

### ISSUE THREAD

**Issue by WajahatAliAbid** [JustNrik/NetUtilities#35]
Is there any documentation that will be helpful in collaboration with this project? The documentation is missing for this project so far. Can you guide me to possible resources which will allow me to contribute to this project?

**Comment by JustNrik** [comment]
Not really (yet), just feel free to PR any utility method you want to share.

**Comment by AraHaan** [comment]
It *could* be possible to have markdown docs and then make an msbuild task that then has a job of "converting" those docs to xml format that is then tasked with outputting them to where they can be included in the xml docs on the source.

It *should* be possible with msbuild nowdays because every IDE that exists should invoke msbuild (and likewise the some targets to invoke that then custom task).

Or have an task that takes the xml docs and generates markdown format docs from it when building (and using the github action ``create-pull-request`` to then have it pull request the doc updates). Either way should work.
